User.destroy_all

u1 = User.create :username => "JS1234", :name => 'John Smith', :email => 'JohnSmith@gmail.com', :password => "chicken", :password_confirmation => "chicken"
u2 = User.create :username => "Ben", :name => 'Ben Jones', :email => 'BenJones@gmail.com', :password => "chicken", :password_confirmation => "chicken"
u3 = User.create :username => "Elizabeth", :name => 'Elizabeth Windsor', :email => 'elizabeth@email.com', :password => "chicken", :password_confirmation => "chicken"
u4 = User.create :username => "Anne A", :name => 'Anne A', :email => 'AnneA@email.com', :password => "chicken", :password_confirmation => "chicken"

puts "User count: #{ User.all.count }"

Recipe.destroy_all

r1 = Recipe.create :name => "Seafood Paella", :image => "http://res.cloudinary.com/esthertan/image/upload/c_limit,h_300,w_200/v1480480211/SeafoodPaella.jpg", :ingredients => "1L (4 cups) fish stock, 1/2 tsp saffron threads, 1 1/2 tablespoons olive oil,300g skinless firm white fish fillets, cut into 4cm pieces, 1 chorizo, thinly sliced diagonally, 1 red onion, thinly sliced, 4 garlic cloves, finely chopped, 2 teaspoons paprika, 1 long fresh red chilli, thinly sliced, 1 small red capsicum, thinly sliced, 1 small yellow capsicum, thinly sliced, 330g (1 1/2 cups) Sunrice arborio rice, 125ml (1/2 cup) white wine, 8 large green prawns, unpeeled, 200g squid tubes, thinly sliced into rings, 80g (1/2 cup) frozen baby peas, Chopped fresh continental parsley, to serve.", :method => "1. Bring stock and saffron to the boil in a saucepan over high heat. Remove from heat and cover to keep warm. 2. Heat the oil in a 34cm (top measurement) paella pan or large frying pan over medium-high heat. Season fish. Cook, turning, for 2 minutes or until almost cooked through. Transfer to a bowl and cover. 3. Add chorizo and cook, stirring, for 2 minutes or until brown. Stir in onion, garlic, paprika, chilli and combined capsicum for 4-5 minutes or until soft. Stir in rice for 1 minute. Stir in wine for 1 minute or until wine evaporates. 4. Add stock mixture to pan, reserving 80ml (1/3 cup). Reduce heat to low. Cook, without stirring, for 15 minutes. 5. Push prawns and squid into rice. Add the reserved stock. Cook for 10 minutes. Add fish. Cook for 5 minutes or until liquid is almost absorbed. 6. Sprinkle with peas. Cover with foil. Rest for 10 minutes. Top with parsley.", :category => "Seafood."
r2 = Recipe.create :name => "Vegetarian Quinoa and Sweet Potato Fried Rice", :image => "http://res.cloudinary.com/esthertan/image/upload/c_limit,h_300,w_200/v1480518913/vegetarian-quinoa-and-sweet-potato-fried-rice-100684-1_ihycr3.jpg", :ingredients => "200g (1 cup) SunRice jasmine rice, 100g (1/2 cup) quinoa, rinsed, 500ml (2 cups) water, 1 tablespoon peanut oil, 2 eggs, lightly whisked, White pepper, to season, 80ml (1/3 cup) gluten-free tamari, 2 teaspoons caster sugar, 1 teaspoon sesame oil, 1 small brown onion, halved, cut into wedges, 2 teaspoons finely chopped fresh ginger, 2 teaspoons finely chopped garlic, 250g sweet potato, peeled, finely chopped, 60ml (1/4 cup) water, 120g cup mushrooms, trimmed, chopped 120g (3/4 cup) frozen peas, defrosted, 1/2 bunch watercress, leaves picked, 3 green shallots, thinly sliced.", :method => "1. Place rice, quinoa and water in a saucepan. Bring to the boil over high heat, stirring occasionally. Cover. Reduce heat to low. Cook for 12 minutes. Remove from heat. Set aside, covered, for 8 minutes. Use a fork to fluff. Spread over a baking tray. Set aside for 1 hour to cool.2. Heat 2 tsp of the peanut oil in a large wok over high heat. Season egg with salt and white pepper. Pour into wok. Cook for 30 seconds, then swirl. Cook for a further 30 seconds. Gently loosen the edge of the omelette with a flat-bladed knife. Roll up. Transfer to a work surface. Cut into thin strips. Use paper towel to wipe wok clean. 3. Combine tamari, sugar and sesame oil in a small bowl. 4. Heat remaining peanut oil over medium-high heat. Stir-fry onion, ginger and garlic for 3 minutes or until golden. Add potato. Toss to coat. Add water. Cook, stirring occasionally, for 5 minutes or until water evaporates and potato is tender. Add mushroom. Stir-fry for 2 minutes. 5 Add rice mixture and peas to the wok and toss to combine. Add tamari mixture and toss until warmed through. Toss through watercress and shallot and top with the omelette slices.", :category => "Quick and Easy."
r3 = Recipe.create :name => "Sticky Ginger Chicken with pickled cucumber salsa", :image => "http://res.cloudinary.com/esthertan/image/upload/c_limit,h_300,w_200/v1480520036/sticky-chicken-wings-with-caramelised-onion-and-coconut-rice-102771-1_zmaoou.jpg", :ingredients => "25g butter, melted, cooled, 1/4 cup dark brown sugar, 2 tablespoons soy sauce, 3 teaspoons fish sauce, 1/4 cup glace ginger, finely chopped, 2 garlic cloves, crushed, 8 small chicken thigh fillets, 1 1/3 cups white long-grain rice, Fresh coriander leaves, to serve, Lime wedges, to serve, 1 Lebanese cucumber, 1 teaspoon coriander seeds, 2 tablespoons rice wine vinegar, 1 teaspoon caster sugar.", :method => "1. Combine butter, sugar, soy, fish sauce, ginger and garlic in a glass or ceramic bowl. Add chicken. Toss to coat. Set aside for 10 minutes. 2. Meanwhile, make Pickled cucumber salsa; Slice cucumbers into very thin rounds. Place in a bowl. Crush coriander seeds between your fingers. Add to bowl with vinegar and sugar. Toss to combine. Cover. Set aside for 15 minutes. 3. Heat a large frying pan over medium-high heat. Cook chicken and marinade for 10 minutes, turning chicken during cooking, until chicken is caramelised and cooked through. 4 Meanwhile, cook rice following packet directions, until tender. 5. Drain cucumber from pickling liquid. Serve chicken with rice, coriander, lime wedges and pickled cucumber salsa.", :category => "Quick and Easy."
r4 = Recipe.create :name => "Malaysian Satay", :image => "http://res.cloudinary.com/esthertan/image/upload/c_limit,h_300,w_200/v1480517075/Malaysian_Satay_l12z7w.jpg", :ingredients => "2 lemongrass stalks (white part only), chopped, 1.5cm piece fresh ginger, peeled, roughly chopped, 1.5cm piece galangal, peeled, roughly chopped, 2 garlic cloves, chopped, 2 eschalots, peeled, roughly chopped, 1 teaspoon ground turmeric, 1 teaspoon ground cumin, 1 teaspoon ground coriander, 2 1/2 tablespoons palm sugar, 1 1/4 teaspoons salt, 500g beef rump steak, trimmed, thinly sliced, 3/4 cup unsalted roasted peanuts, plus extra chopped peanuts to serve, 2 tablespoons peanut oil, 2 teaspoons sambal belacan, 2 teaspoons tamarind paste, 2 teaspoons lime juice, 3 cups steamed jasmine rice, 2 Lebanese cucumbers, chopped, 1 red onion, cut into wedges, Lime wedges, to serve.", :method => "1. Process lemongrass, ginger, galangal, garlic and eschalot in a small food processor until smooth. Transfer 1/2 the mixture to a large glass or ceramic bowl. Add turmeric, cumin, coriander, 1 tablespoon sugar and 1/4 teaspoon salt. Stir to combine. Add beef. Stir to coat. Cover. Transfer remaining lemongrass mixture to a small bowl. Cover. Refrigerate beef mixture and lemongrass mixture for 2 hours. 2. Place peanuts in a small food processor. Process until finely chopped. 3. Heat oil in a saucepan over medium heat. Add remaining lemongrass mixture. Cook for 2 minutes or until fragrant. Add sambal belacan. Cook for 1 minute. Add chopped peanuts, 3/4 cup water, tamarind, lime juice, and remaining sugar and salt. Bring to the boil. Reduce heat to low. Simmer for 20 to 25 minutes or until slightly thickened, adding extra water if satay sauce becomes too thick. 4. Thread beef onto 12 skewers. Heat a non-stick frying pan over medium-high heat. Cook skewers, in batches, for 1 minute each side or until just cooked through. Sprinkle with extra peanuts. Serve with satay sauce, rice, cucumber, onion and lime wedges.", :category => "Entertaining."
r5 = Recipe.create :name => "Cabonara Pizza", :image => "http://res.cloudinary.com/esthertan/image/upload/c_limit,h_300,w_200/v1480520252/carbonara-pizza-our-most-recent-recipes-of-the-day-104195-2_dstnbq.jpg", :ingredients => "600g pkt (2 bases) plain pizza bases, 425g carbonara sauce, 85g (3/4 cup) Il Migliore Shredded Mozzarella & Gouda Blend, 100g mild pancetta, sliced, 125g button mushrooms, sliced, 3 green shallots, trimmed, thinly sliced diagonally.", :method => "1. Preheat oven to 230C/210C fan forced. Lightly grease 2 pizza trays. 2. Spread the pizza bases with the sauce. Sprinkle over the cheese. Top with pancetta and mushrooms. Sprinkle with half the shallot. Bake for 15-20 minutes or until golden. Sprinkle with remaining shallot.", :category => "Entertaining."
r6 = Recipe.create :name => "Vietnamese Pork Ribs", :image => "http://res.cloudinary.com/esthertan/image/upload/c_limit,h_300,w_200/v1480521442/vietnamese-pork-ribs-110055-1_qz5rhs.jpg", :ingredients => "2 racks (1.5kg) pork ribs, Extra virgin olive oil, for brushing, Small red chilli, sliced, to serve, Fresh coriander sprigs, to serve, 2 small red chillies, finely chopped, 6 garlic cloves, crushed, 1/2 cup lime juice, 1/4 cup fish sauce, 1/3 cup brown sugar, 2 stalks lemongrass (white part only), bruised, sliced into 1cm pieces.", :method => "1. Make Marinade. Combine chilli, garlic, lime juice, fish sauce, sugar and lemongrass in a small bowl. Transfer to a large snap-lock bag. Add ribs. Massage ribs to coat in marinade. Refrigerate for 3 hours or overnight, if time permits. 2. Preheat oven to 200C/180C fan-forced. Transfer ribs to a large baking dish. Add 1/2 cup water. Cover dish tightly with foil. Bake for 1 hour. Remove and discard foil. Turn ribs. Bake for a further 30 minutes or until ribs are tender. Transfer to a board. Carefully cut each rack into single ribs and return to baking dish. 3. Brush a barbecue grill or chargrill pan with oil. Heat on high heat. Toss ribs in pan juices. Cook ribs for 1 minute each side or until charred. Transfer to a serving plate. Sprinkle with chilli and coriander sprigs. Serve.", :category => "Quick and Easy."
r7 = Recipe.create :name => "Prawn,Peach and Goat's cheese salad", :image => "http://res.cloudinary.com/esthertan/image/upload/c_limit,h_300,w_200/v1480518398/prawn-peach-and-goats-cheese-salad-118428-1_xdz5wr.jpg", :ingredients => "150g snow peas, trimmed, 1 bunch watercress, leaves picked, 2 yellow peaches, stoned, thinly sliced, 3/4 cup fresh mint leaves, 36 (about 1kg) medium cooked prawns, peeled leaving tails intact, deveined, 100g goat's cheese, 2 tablespoons lime juice, 2 tablespoons extra virgin olive oil, 1 tablespoon white wine vinegar, 1 garlic clove, crushed, 1/2 long red chilli, seeded, finely chopped, 1/2 teaspoon caster sugar.", :method => "1. Cook the snow peas in a saucepan of boiling water for 2 mins or until bright green and tender crisp. Refresh under cold water. Drain well. Use a sharp knife to cut the snow peas in half diagonally. 2. To make the lime & chilli dressing, combine the lime juice, oil, vinegar, garlic, chilli and sugar in a screw-top jar and shake until well combined. Season. 3. Toss the watercress, peach, mint leaves, prawns and snow peas in a bowl. Arrange on a serving platter. Crumble over goat’s cheese. Drizzle with dressing.", :category => "Entertaining"
r8 = Recipe.create :name => "Zucchini,haloumi and preserved lemon fritters", :image => "http://res.cloudinary.com/esthertan/image/upload/c_limit,h_300,w_200/v1480520247/zucchini-haloumi-and-preserved-lemon-fritters-101162-1_jt1clb.jpg", :ingredients => "2 large zucchini, coarsely grated, 1 red onion, coarsely grated, 2 teaspoons preserved lemon, finely chopped , 2 teaspoons dried oregano, 150g haloumi, coarsely grated, 1/2 cup plain flour, 1 egg, lightly beaten, 1/3 cup Greek-style yoghurt, Small fresh coriander leaves, to serve.", :method => "1. Preheat oven to 200C/180C fan-forced. Line a baking tray with baking paper. 2. Using hands, squeeze grated zucchini and onion to remove excess liquid. Transfer to a bowl. Add preserved lemon, oregano, haloumi, flour and egg. Season with salt and pepper. Stir to combine. 3. Roll heaped tablespoons of mixture to make 16 balls. Place on prepared tray. Using a fork, flatten slightly. Bake for 25 minutes, turning halfway through, or until golden and firm. Set aside to cool for 5 minutes. 4. Top each fritter with a teaspoon of yoghurt. Season with pepper. Sprinkle with coriander. Serve.", :category => "Quick and Easy."
r9 = Recipe.create :name => "Green bean salad with cumin & orange dressing", :image => "http://res.cloudinary.com/esthertan/image/upload/c_limit,h_300,w_200/v1480553861/green-bean-salad-with-cumin-orange-dressing-87000-1_o623ie.jpg" , :ingredients => "700g green round beans, trimmed, 2 teaspoons cumin seeds, 60ml (1/4 cup) fresh orange juice, 50g butter, chilled, chopped, 1 tablespoon finely grated orange rind, 80g Lucky Natural Sliced Almonds.", :method => "1. Cook the beans in a large saucepan of boiling water for 3-4 minutes or until bright green and tender crisp. Drain and refresh under cold running water. Return to the pan. 2. Meanwhile, cook the cumin seeds in a small frying pan over medium heat for 2-3 minutes or until aromatic. Add the orange juice and bring just to the boil. Use a balloon whisk to gradually whisk in the butter, 1 piece at a time, until the butter melts and is well combined. Remove from heat. Add the orange rind and season with salt and pepper. 3. Add the orange mixture and almonds to the beans and toss gently to combine. Transfer salad to a serving platter.", :category => "Receipes."
r10 = Recipe.create :name => "Vegetarian Spaghetti", :image => "http://res.cloudinary.com/esthertan/image/upload/c_limit,h_300,w_200/v1480554019/vegetarian-spaghetti-45712-1_dujhek.jpg", :ingredients => "1 tablespoon olive oil, 1 large brown onion, chopped, 2 garlic cloves, crushed, 2 medium zucchini, chopped, 200g yellow squash, chopped, 1 medium eggplant, chopped, 3/4 cup red lentils, rinsed, drained, 2 large tomatoes, chopped, 700g bottle Italian tomato pasta sauce, 300g broccoli, cut into small florets, 1/4 cup chopped fresh flat-leaf parsley leaves, 375g dried spaghetti pasta, shaved vegetarian hard cheese, to serve.", :method => "1. Heat oil in a large, heavy-based saucepan over medium heat. Add onion and garlic. Cook for 5 minutes or until onion is just soft. 2. Add zucchini, squash and eggplant. Cook, stirring, for 5 minutes. Add lentils, tomato, pasta sauce and 1/2 cup cold water. Bring to the boil. Reduce heat to medium-low. Cook, covered, for 20 minutes. Add broccoli. Cook, uncovered, for 10 minutes or until lentils are tender. 3. Meanwhile, cook pasta in a saucepan of boiling, salted water, following packet directions, until tender. Drain. 4. Divide pasta between bowls. Top with vegetable sauce. Serve with parmesan cheese.", :category => "Receipes."
r11 = Recipe.create :name => "Seafood Risotto", :image => "http://res.cloudinary.com/esthertan/image/upload/c_limit,h_300,w_200/v1480554115/seafood-risotto-21255-1_qusble.jpg", :ingredients => "750ml (3 cups) fish stock, 375ml (2 1/2 cups) hot water, 2 teaspoons olive oil, 1 brown onion, chopped, 330g (1 1/2 cups) arborio rice, 16 (about 400g) black mussels, debearded, 12 (about 300g) cooked prawns, peeled leaving tails intact, 2 teaspoons garlic pepper sauce (Tabasco brand), 2 tablespoons chopped fresh continental parsley, Salt & freshly ground black pepper.", :method => "1. Combine the stock and water in a medium saucepan, and bring to the boil over high heat. Reduce heat to low and hold at a gentle simmer. 2. Meanwhile, heat oil in a large frying pan over medium-high heat. Add onion and cook, stirring, for 2 minutes or until soft. Add rice and cook for 30 seconds or until grains appear slightly glassy. Increase heat to high. 3. Add 1 1/4 cups (310ml) of simmering stock mixture to rice, stirring with a wooden spoon, and cook for 1-2 minutes or until liquid is absorbed. Continue to add stock mixture, 1 1/4 cups at a time, stirring. Allow all liquid to be absorbed before adding more. Add mussels to pan with last portion of stock mixture. Cook for 2 minutes then add prawns and garlic pepper sauce. Cook for 2 minutes or until mussels have opened and rice is tender yet firm to the bite. (The rice will take about 15 minutes to cook. 4. Remove from heat, discard any unopened mussels. Stir in 1 tablespoon of parsley. Season with salt and pepper. Serve sprinkled with remaining parsley.", :category => "Receipes."
r12 = Recipe.create :name => "Apricot Chicken", :image => "http://res.cloudinary.com/esthertan/image/upload/c_limit,h_300,w_200/v1480554232/apricot-chicken-2996-1_b4rojy.jpg", :ingredients => "1/2 cup plain flour, 8 skinless chicken thigh cutlets or drumsticks, trimmed, 2 tablespoons olive oil, 1 large brown onion, cut into thin wedges, 2 garlic cloves, crushed, 1 tablespoon Moroccan seasoning blend, 405ml can apricot nectar, 1/2 cup dried apricots, 1 cup couscous, 1 cup boiling water, 1/3 cup fresh flat-leaf parsley leaves.", :method => "1. Place flour in a shallow dish. Season with salt and pepper. Toss chicken pieces in flour, shaking off excess. 2. Heat 1 tablespoon oil in a large, deep heavy-based frying pan over medium heat. Cook chicken, in batches, for 2 to 3 minutes each side or until golden, adding extra oil if needed. Transfer to a plate. Set aside. 3. Heat remaining oil in pan. Add onion and garlic. Cook, stirring occasionally, for 5 minutes or until tender. Sprinkle seasoning over onion and stir well to combine. Stir in nectar. Bring to the boil. Reduce heat to low. Return chicken to pan. Cover. Cook for 20 minutes. 4. Add apricots to pan, pushing into the sauce. Cook, uncovered, for a further 20 to 25 minutes or until chicken is cooked through and sauce has thickened. 5. Meanwhile, place couscous in a heatproof bowl. Pour over boiling water. Cover. Stand for 5 minutes or until water is absorbed. Stir with a fork to separate grains. Spoon couscous onto plates. Top with chicken and sauce. Sprinkle with parsley. Serve.", :category => "Quick and Easy."

puts "Recipe count: #{Recipe.all.count}"

u1.recipes << r1 << r2 << r3
u2.recipes << r4 << r5 << r6
u3.recipes << r7 << r8 << r9
u4.recipes << r10 << r11 << r12

Cuisine.destroy_all

c1 = Cuisine.create :style => "Spanish"
c2 = Cuisine.create :style => "Malaysian"
c3 = Cuisine.create :style => "Vietnamese"
c4 = Cuisine.create :style => "Italian"

puts "Cuisine count: #{Cuisine.all.count}"

c1.recipes << r1 << r2 << r3
c2.recipes << r4 << r5 << r6
c3.recipes << r7 << r8 << r9
c4.recipes << r10 << r11 << r12
